package com.ingotpowered.api;

/**
 * Created by Matt on 08/09/14.
 */
public enum Material {

    AIR(0, (byte) 0, "Air"),
    STONE(1, (byte) 0, "Stone"),
    GRANITE(1, (byte) 1, "Granite"),
    DIORITE(1, (byte) 3, "Diorite"),
    POLISHED_DIORITE(1, (byte) 4, "Polished Diorite"),
    ANDESITE(1, (byte) 4, "Andesite"),
    POLISHED_ANDESITE(1, (byte) 5, "Polished Andesite"),
    GRASS(2, (byte) 0, "Grass"),
    DIRT(3, (byte) 0, "Dirt"),
    COARSE_DIRT(3, (byte) 1, "Coarse Dirt"),
    PODZOL(3, (byte) 2, "Podzol"),
    COBBLESTONE(4, (byte) 0, "Cobblestone"),
    OAK_PLANKS(5, (byte) 0, "Oak Wood Planks"),
    SPRUCE_PLANKS(5, (byte) 1, "Spruce Wood Planks"),
    BIRCH_PLANKS(5, (byte) 2, "Birch Wood Planks"),
    JUNGLE_PLANKS(5, (byte) 3, "Jungle Wood Planks"),
    ACACIA_PLANKS(5, (byte) 4, "Acacia Wood Planks"),
    DARK_PLANKS(5, (byte) 5, "Dark Oak Wood Planks"),
    OAK_SAPLING(6, (byte) 0, "Oak Sapling"),
    SPRUCE_SAPLING(6, (byte) 1, "Spruce Sapling"),
    BIRCH_SAPLING(6, (byte) 2, "Birch Sapling"),
    JUNGLE_SAPLING(6, (byte) 3, "Jungle Sapling"),
    ACACIA_SAPLING(6, (byte) 4, "Acacia Sapling"),
    DARK_SAPLING(6, (byte) 5, "Dark Oak Sapling"),
    BEDROCK(7, (byte) 0, "Bedrock"),
    FLOWING_WATER(8, (byte) 0, "Flowing Water"),
    STILL_WATER(9, (byte) 0, "Still Water"),
    FLOWING_LAVA(10, (byte) 0, "Flowing Lava"),
    STILL_LAVA(11, (byte) 0, "Still Lava"),
    SAND(12, (byte) 0, "Sand"),
    RED_SAND(12, (byte) 1, "Red Sand"),
    GRAVEL(13, (byte) 0, "Gravel"),
    GOLD_ORE(14, (byte) 0, "Gold Ore"),
    IRON_ORE(15, (byte) 1, "Iron Ore"),
    COAL_ORE(16, (byte) 0, "Coal Ore"),
    OAK_LOG(17, (byte) 0, "Oak Logs"),
    SPRUCE_LOG(17, (byte) 1, "Spruce Logs"),
    BIRCH_LOG(17, (byte) 2, "Birch Logs"),
    JUNGLE_LOG(17, (byte) 3, "Jungle Logs"),
    OAK_LEAVES(18, (byte) 0, "Oak Leaves"),
    SPRUCE_LEAVES(18, (byte) 1, "Spruce Leaves"),
    BIRCH_LEAVES(18, (byte) 2, "Birch Leaves"),
    JUNGLE_LEAVES(18, (byte) 3, "Jungle Leaves"),
    SPONGE(19, (byte) 0, "Sponge"),
    WET_SPONGE(19, (byte) 1, "Wet Sponge"),
    GLASS(20, (byte) 0, "Glass"),
    LAPIS_ORE(21, (byte) 0, "Lapis Lazuli Ore"),
    LAPIS_BLOCK(22, (byte) 0, "Lapis Lazuli Block"),
    DISPENSER(23, (byte) 0, "Dispenser"),
    SANDSTONE(24, (byte) 0, "Sandstone"),
    CHISELED_SANDSTONE(24, (byte) 1, "Chiseled Sandstone"),
    SMOOTH_SANDSTONE(24, (byte) 2, "Smooth Sandstone"),
    NOTE_BLOCK(25, (byte) 0, "Note Block"),
    BED(26, (byte) 0, "Bed"),
    POWERED_RAIL(27, (byte) 0, "Powered Rail"),
    DETECTOR_RAIL(28, (byte) 0, "Detector Rail"),
    STICKY_PISTON(29, (byte) 0, "Sticky Piston"),
    COBWEB(30, (byte) 0, "Cob Web"),
    DEAD_SHRUB(31, (byte) 0, "Dead Shrub"),
    TALL_GRASS(31, (byte) 1, "Grass"),
    FERN(31, (byte) 2, "Fern"),
    PISTON(33, (byte) 0, "Piston"),
    PISTON_HEAD(34, (byte) 0, "Piston Head"),
    WHITE_WOOL(35, (byte) 0, "White Wool"),
    ORANGE_WOOL(35, (byte) 1, "Orange Wool"),
    MAGENTA_WOOL(35, (byte) 2, "Magenta Wool"),
    LIGHTBLUE_WOOL(35, (byte) 3, "Light Blue Wool"),
    YELLOW_WOOL(35, (byte) 4, "Yellow Wool"),
    LIME_WOOL(35, (byte) 5, "Lime Wool"),
    PINK_WOOL(35, (byte) 6, "Pink Wool"),
    GRAY_WOOL(35, (byte) 7, "Gray Wool"),
    LIGHTGRAY_WOOL(35, (byte) 8, "Light Gray Wool"),
    CYAN_WOOL(35, (byte) 9, "Cyan Wool"),
    PURPLE_WOOL(35, (byte) 10, "Purple Wool"),
    BLUE_WOOL(35, (byte) 11, "Blue Wool"),
    BROWN_WOOL(35, (byte) 12, "Brown Wool"),
    GREEN_WOOL(35, (byte) 13, "Green Wool"),
    RED_WOOL(35, (byte) 14, "Red Wool"),
    BLACK_WOOL(35, (byte) 15, "Black Wool"),
    DANDELION(37, (byte) 0, "Dandelion"),
    POPPY(38, (byte) 0, "Poppy"),
    BLUE_ORCHID(38, (byte) 1, "Blue Orchid"),
    ALLIUM(38, (byte) 2, "Allium"),
    AZURE_BLUET(38, (byte) 3, "Azure Bluet"),
    RED_TULIP(38, (byte) 4, "Red Tulip"),
    ORANGE_TULIP(38, (byte) 5, "Orange Tulip"),
    WHITE_TULIP(38, (byte) 6, "White Tulip"),
    PINK_TULIP(38, (byte) 7, "Pink Tulip"),
    OXEYE_DAISY(38, (byte) 8, "Oxeye Daisy"),
    BROWN_MUSHROOM(39, (byte) 0, "Brown Mushroom"),
    RED_MUSHROOM(40, (byte) 0, "Red Mushroom"),
    GOLD_BLOCK(41, (byte) 0, "Gold Block"),
    IRON_BlOCK(42, (byte) 0, "Iron Block"),
    DOUBLE_STONE_SLAB(43, (byte) 0, "Double Stone Slab"),
    DOUBLE_SANDSTONE_SLAB(43, (byte) 1, "Double Sandstone Slab"),
    DOUBLE_WOOD_SLAB(43, (byte) 2, "Double Wooden Slab"),
    DOUBLE_COBBLESTONE_SLAB(43, (byte) 3, "Double Cobblestone Slab"),
    DOUBLE_BRICK_SLAB(43, (byte) 4, "Double Brick Slab"),
    DOUBLE_STONE_BRICK_SLAB(43, (byte) 5, "Double Stone Brick Slab"),
    DOUBLE_NETHER_SLAB(43, (byte) 6, "Double Nether Brick Slab"),
    DOUBLE_QUARTZ_SLAB(43, (byte) 7, "Double Quartz Slab"),
    STONE_SLAB(44, (byte) 0, "Stone Slab"),
    SANDSTONE_SLAB(44, (byte) 1, "Sandstone Slab"),
    WOODEN_SLAB(44, (byte) 2, "Wooden Slab"),
    COBBLESTONE_SLAB(44, (byte) 3, "Cobblestone Slab"),
    BRICK_SLAB(44, (byte) 4, "Brick Slab"),
    STONE_BRICK_SLAB(44, (byte) 5, "Stone Brick Slab"),
    NETHER_BRICK_SLAB(44, (byte) 6, "Nether Brick Slab"),
    QUARTZ_SLAB(44, (byte) 7, "Quartz Slab"),
    BRICKS(45, (byte) 0, "Bricks"),
    TNT(46, (byte) 0, "TNT"),
    BOOKSHELF(47, (byte) 0, "Bookshelf"),
    MOSS_STONE(48, (byte) 0, "Moss Stone"),
    OBSIDIAN(49, (byte) 0, "Obsidian"),
    TORCH(50, (byte) 0, "Torch"),
    FIRE(51, (byte) 0, "Fire"),
    MONSTER_SPAWNER(52, (byte) 0, "Monster Spawner"),
    OAK_STAIRS(53, (byte) 0, "Oak Wood Stairs"),
    CHEST(54, (byte) 0, "Chest"),
    REDSTONE_WIRE(55, (byte) 0, "Redstone Wire"),
    DIAMOND_ORE(56, (byte) 0, "Diamond Ore"),
    DIAMOND_BLOCK(57, (byte) 0, "Diamond Block"),
    CRAFTING_TABLE(58, (byte) 0, "Crafting Table"),
    WHEAT_CROPS(59, (byte) 0, "Wheat Crops"),
    FARMLAND(60, (byte) 0, "Farmland"),
    FURNACE(61, (byte) 0, "Furnace"),
    BURNING_FURNACE(62, (byte) 0, "Burning Furnace"),
    STANDING_SIGN(63, (byte) 0, "Standing Sign"),
    OAK_DOOR(64, (byte) 0, "Oak Wood Door"),
    LADDER(65, (byte) 0, "Ladder"),
    RAIL(66, (byte) 0, "Rail"),
    COBBLESTONE_STAIRS(67, (byte) 0, "Cobblestone Stairs"),
    WALL_SIGN(68, (byte) 0, "Wall Sign"),
    LEVER(69, (byte) 0, "Lever"),
    STONE_PRESSURE_PLATE(70, (byte) 0, "Stone Pressure Plate"),
    IRON_DOOR(71, (byte) 0, "Iron Door"),
    WOODEN_PRESSURE_PLATE(72, (byte) 0, "Wooden Pressure Plate"),
    REDSTONE_ORE(73, (byte) 0, "Redstone Ore"),
    GLOWING_REDSTONE_ORE(74, (byte) 0, "Glowing Redstone Ore"),
    REDSTONE_TORCH_OFF(75, (byte) 0, "Redstone Torch (off)"),
    REDSTONE_TORCH_ON(76, (byte) 0, "Redstone Torch (on)"),
    STONE_BUTTON(77, (byte) 0, "Stone Button"),
    SNOW(78, (byte) 0, "Snow"),
    ICE(79, (byte) 0, "Ice"),
    SNOW_BLOCK(80, (byte) 0, "Snow Block");

    private final int itemId;

    private final String itemName;

    private Material(int itemId, byte dataValue, String itemName){
        this.itemId = itemId;
        this.itemName = itemName;
    }

    public int getItemId(){
        return itemId;
    }

    public String getItemName(){
        return itemName;
    }
}
